
SYSTEM_NAME = "Reflective Dialogue System (RDS)"
VERSION = "1.0"
DEBUG_MODE = True  

MEMORY_LIMIT = 1000  
MEMORY_RETENTION_DAYS = 30 

SELF_PROMPT_INTERVAL = 10 
MAX_PROMPTS_PER_SESSION = 5  
PROMPTING_THRESHOLD = 0.7

SENTIMENT_API_ENABLED = False  
SENTIMENT_CONFIDENCE_THRESHOLD = 0.6 
DEFAULT_SENTIMENT_ANALYSIS_MODE = "simple"

DEFAULT_CONTEXT_WINDOW_SIZE = 5 

AUTO_LEARNING_ENABLED = True  
LEARNING_RATE = 0.01  

API_LIMITS = {
    "sentiment_analysis": 1000,  
    "external_data": 500, 
}

LOGGING_ENABLED = True  
LOG_FILE_PATH = "./logs/system.log" 
LOG_LEVEL = "DEBUG" 

ENABLE_EXTERNAL_CONTEXT_FETCHING = False

